# Generated by Django 5.0.2 on 2024-02-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='imagen_default.png', upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('unitario', 'Precio Unitario'), ('media-doc', 'Media Docena'), ('docena', 'Docena'), ('por-kilo', 'Kilo')], default='unitario', max_length=9, verbose_name='Tipo de Precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
    ]
